instrument: RS01SBPS-SF01A-3C-PARADA101
module: mi.instrument.satlantic.par_ser_600m.ooicore.driver
klass: InstrumentDriver
event_port: 14111
command_port: 15111
port_agent_config:
  addr: uft20
  port: 12111
  cmd_port: 13111
startup_config:
  parameters:
   'firmware': '1.0.0'
   'serial': '4278190306'
   'instrument': 'SATPAR'
expected_particles:
- parad_sa_sample
- parad_sa_config
starting_state: DRIVER_STATE_AUTOSAMPLE
#script:
#- [execute, DRIVER_EVENT_ACQUIRE_STATUS]
#- [execute, DRIVER_EVENT_ACQUIRE_SAMPLE]
#- [execute, DRIVER_EVENT_START_AUTOSAMPLE]
#- [sleep, 5]
#- [execute, DRIVER_EVENT_STOP_AUTOSAMPLE]
