instrument: RS03AXPS-SF03A-4A-NUTNRA301
module: mi.instrument.satlantic.suna_deep.ooicore.driver
klass: InstrumentDriver
event_port: 14138
command_port: 15138
port_agent_config: 
  addr: uft20
  port: 12138
  cmd_port: 13138
startup_config:
  parameters:
    nmlgtspl: 2
    tlgtsmpl: 30
    opermode: 'Polled'
    operctrl: 'Samples'
    lgtsmpls: 5
    drksmpls: 1
    lgtdurat: 10
    drkdurat: 5
expected_particles:
- nutnr_a_sample
- nutnr_a_status
- nutnr_a_test
starting_state: DRIVER_STATE_COMMAND
#script:
#- [execute, DRIVER_EVENT_ACQUIRE_STATUS]
#- [execute, DRIVER_EVENT_ACQUIRE_SAMPLE]
#- [execute, DRIVER_EVENT_START_AUTOSAMPLE]
#- [sleep, 5]
#- [execute, DRIVER_EVENT_STOP_AUTOSAMPLE]
#- [sleep, 5]

