instrument: RS03AXPS-SF03A-2A-CTDPFA302
module: mi.instrument.seabird.sbe16plus_v2.ctdpf_sbe43.driver 
klass: InstrumentDriver
event_port: 14136
command_port: 15136
port_agent_config:
  addr: uft20
  port: 12136
  cmd_port: 13136
startup_config:
  parameters:
expected_particles:
- ctdpf_sbe43_sample
- ctdpf_sbe43_status
- ctdpf_sbe43_calibration_coefficients
- ctdpf_sbe43_hardware
- ctdpf_sbe43_configuration
- ctdpf_sbe43_settings
starting_state: DRIVER_STATE_AUTOSAMPLE
#script:
#- [execute, DRIVER_EVENT_ACQUIRE_STATUS]
#- [sleep, 10]
#- [execute, DRIVER_EVENT_START_AUTOSAMPLE]
#- [sleep, 90000]
#- [execute, DRIVER_EVENT_STOP_AUTOSAMPLE]
#- [sleep, 10]
